//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YDFrame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public string PassWord { get; set; }
    }
}
